puz_puz_homepage:
    path:     /
    defaults: { _controller: PUZPuzBundle:Default:index }

puz_playlist_create:
    path:     /playlist
    defaults: { _controller: PUZPuzBundle:Playlist:create }
    methods: POST

puz_playlist_show:
    path:     /playlist/{id}
    defaults: { _controller: PUZPuzBundle:Playlist:show }
    methods: GET

puz_playlist_list:
    path:     /playlist
    defaults: { _controller: PUZPuzBundle:Playlist:list }
    methods: GET